@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Пользователь", "Использует приложение для управления отоплением и просмотра температуры")

Person(user, "Пользователь", "Просматривает температуру и управляет отоплением")
Person(specialist, "Специалист", "Выполняет установку устройств")

System(system, "Монолитное приложение\n'Умный дом'", "Обеспечивает управление системами отопления и мониторинг температуры")

System_Ext(heating_system, "Система отопления", "Включает или выключает отопление")
System_Ext(temp_sensor, "Датчик температуры", "Измеряет температуру и передает о ней данные")

' Flows
Rel(user, system, "Использует через веб-браузер")
'Rel(specialist, heating_system, "Устанавливает устройства")
Rel(specialist, system, "Подключает системы отопления и датчики к приложению")
Rel(system, heating_system, "Передает команду управления отоплением")
Rel(system, temp_sensor, "Запрашивает данные о температуре")

@enduml
