@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов

Container(spa, "Single-Page App", "JavaScript, Angular", "Предоставляет пользователям все функции системы через их веб-браузер")

Container_Boundary(api_app, "API Application") {
  Component(api_gateway, "API Gateway", "Node.js/Kong/Nginx", "Точка входа для пользователей и приложений")
  Component(user_srv, "User Management Service", "Python", "Аутентификация, авторизация, роли")
  Component(house_srv, "House Management Service", "Python", "Дома, связи, управляющие данные")
  Component(device_srv, "Device Management Service", "Python", "Управление устройствами и их привязка")
  Component(telemetry_srv, "Telemetry Service", "Python", "Сбор данных с устройств")
  Component(control_srv, "Control Service", "Python", "Управление сценариями и состоянием устройств")
  Component(integration_srv, "Integration Service", "Python", "Интеграция с физическими устройствами")
  Component(notify_srv, "Notification Service", "Python", "Рассылка уведомлений")
  ComponentDb(userdb, "UserDB", "PostgreSQL", "Пользователи")
  ComponentDb(housedb, "HouseDB", "PostgreSQL", "Дома")
  ComponentDb(devicedb, "DeviceDB", "PostgreSQL", "Устройства")
  ComponentDb(telemetrydb, "TelemetryDB", "TimescaleDB", "Телеметрия")
  ComponentDb(heatingdb, "HeatingDB", "PostgreSQL", "Режимы и история управления")
  ComponentQueue(broker, "Message Broker", "Kafka", "Асинхронная коммуникация с помощью сообщений")
}

Rel(spa, api_gateway, "HTTP")
Rel(api_gateway, user_srv, "REST")
Rel(api_gateway, house_srv, "REST")
Rel(api_gateway, device_srv, "REST")
Rel(api_gateway, control_srv, "REST")
Rel(api_gateway, telemetry_srv, "REST")

Rel(user_srv, userdb, "SQL")
Rel(house_srv, housedb, "SQL")
Rel(device_srv, devicedb, "SQL")
Rel(telemetry_srv, telemetrydb, "SQL")
Rel(control_srv, heatingdb, "SQL")

Rel(control_srv, integration_srv, "REST")
Rel(integration_srv, device_srv, "REST")
Rel(integration_srv, broker, "отправляет сообщения")
Rel(device_srv, broker, "читает сообщения")
Rel(telemetry_srv, broker, "читает сообщения")
Rel(control_srv, broker, "отправляет/читает сообщения")

Rel(broker, notify_srv, "читает сообщения")

@enduml