@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Диаграмма контейнеров

Container(spa, "Single-Page App", "JavaScript, Angular", "Предоставляет пользователям все функции системы через их веб-браузер")

Container_Boundary(api_app, "API Application") {
  Container(api_gateway, "API Gateway", "Node.js/Kong/Nginx", "Точка входа для пользователей и приложений")
  Container(user_srv, "User Management Service", "Python", "Аутентификация, авторизация, роли")
  Container(house_srv, "House Management Service", "Python", "Дома, связи, управляющие данные")
  Container(device_srv, "Device Management Service", "Python", "Управление устройствами и их привязка")
  Container(telemetry_srv, "Telemetry Service", "Python", "Сбор данных с устройств")
  Container(control_srv, "Control Service", "Python", "Управление сценариями и состоянием устройств")
  Container(integration_srv, "Integration Service", "Python", "Интеграция с физическими устройствами")
  Container(notify_srv, "Notification Service", "Python", "Рассылка уведомлений")
  ContainerDb(userdb, "UserDB", "PostgreSQL", "Пользователи")
  ContainerDb(housedb, "HouseDB", "PostgreSQL", "Дома")
  ContainerDb(devicedb, "DeviceDB", "PostgreSQL", "Устройства")
  ContainerDb(telemetrydb, "TelemetryDB", "TimescaleDB", "Телеметрия")
  ContainerDb(heatingdb, "HeatingDB", "PostgreSQL", "Режимы и история управления")
}

Rel(spa, api_gateway, "HTTP")

Rel(api_gateway, user_srv, "REST")
Rel(api_gateway, house_srv, "REST")
Rel(api_gateway, device_srv, "REST")
Rel(api_gateway, control_srv, "REST")
Rel(api_gateway, telemetry_srv, "REST")

Rel(user_srv, userdb, "SQL")
Rel(house_srv, housedb, "SQL")
Rel(device_srv, devicedb, "SQL")
Rel(telemetry_srv, telemetrydb, "SQL")
Rel(control_srv, heatingdb, "SQL")

Rel(control_srv, integration_srv, "REST")
Rel(integration_srv, device_srv, "REST")
Rel(telemetry_srv, integration_srv, "REST")

Rel(control_srv, notify_srv, "REST")
Rel(user_srv, notify_srv, "REST")
Rel(house_srv, notify_srv, "REST")
Rel(device_srv, notify_srv, "REST")


@enduml